### ISSUE TITLE
Failed to get pbm status errors

### ISSUE THREAD

**Issue by gruyaume** [canonical/mongodb-k8s-operator#212]
## Steps to reproduce
1. juju deploy mongodb-k8s
2. juju deploy sdcore-nrf
3. juju integrate mongodb-k8s sdcore-nrf

## Expected behavior
No errors

## Actual behavior

Failed to get pbm status errors in charm.

## Versions

Operating system: Ubuntu 22.04
Juju CLI: 3.1.6
Juju agent: 3.1.6
Charm revision: 6/edge (Revision 37)
microk8s: v1.27.6

## Log output
```
unit-mongodb-k8s-0: 07:37:32 ERROR unit.mongodb-k8s/0.juju-log Failed to get pbm status. non-zero exit code 1 executing ['/usr/bin/pbm', 'status', '-o', 'json'], stdout='{"Error":"get status of pitr: check for errors: get current epoch: get config: get: mongo: no documents in result"}\n', stderr=''
```

**Comment by MiaAltieri** [comment]
Hi @gruyaume from what I can tell this is infact an issue in the log messages. I'm happy you noticed it since poor logging can impact how users understand the charm, thanks for pointing this out :) 

The log messages come from the shared mongodb libraries (which are hosted & maintained on the VM side) right now there are two open PRs to fix this: [6/edge](https://github.com/canonical/mongodb-operator/pull/305) and [5/edge](https://github.com/canonical/mongodb-operator/pull/306) once these are merged we can update the libraries on the k8s side.

Other than that though, the charm should be functional. Did you encounter any functional errors or only the incorrect log?

**Comment by gruyaume** [comment]
Perfect, thank you @MiaAltieri
